### ISSUE TITLE
Rectification of the word 'Grammarly'

### ISSUE THREAD

**Issue by mustafaumar** [communityleads/cm-tools#12]
![Screenshot (633)](https://github.com/communityleads/cm-tools/assets/80973575/2380a064-4c94-41db-ae0b-3b62a475ad2f)
The word 'Grammarly' is wrongly misspelt. I intend correcting it.

**Comment by codejagaban** [comment]
This PR: [Pull:13](https://github.com/communityleads/cm-tools/pull/13) fixes this issue
